name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build_site:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          touch .env
          echo API_URL=${{secrets.API_URL}} > .env
      - name: Navigate to client directory
        run: |
          cd client

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true

      - name: build
        env:
          BASE_PATH: '/'
        run: |
          ls
          pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
