name: Deploy the server to AWS EC2 instance
on:
  push:
    branches: [ main ]

jobs:
  Containerize:
    name: Build and push docker image
    runs-on: ubuntu-latest
    environment: "AWS Deployment"
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create the .env file
        run: echo ${{secrets.DATABASE_URL}} > .env_docker

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{vars.DOCKERHUB_USERNAME}}/portfolio-server:latest

  deploy:
    name: Run the docker image on host machine
    runs-on: ubuntu-latest
    environment: "AWS Deployment"
    steps:
      - name: Create private key file
        run: |
          mkdir key
          echo ${{secrets.AWS_SSH_KEY}} > key/private.pem
          chmod 600 private.pem

      - name: Start the deployment process
        run: |
          ssh -o StrictHostKeyChecking=no -i key/private.pem ${{secrets.AWS_SSH_USERNAME}}@${{secrets.AWS_SSH_IP}}
          ./docker_run.sh