name: Deploy the server to AWS EC2 instance
on:
  push:
    branches: [ main ]

jobs:
  Containerize:
    name: Build and push docker image
    runs-on: ubuntu-latest
    environment: "AWS Deployment"
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create the .env file
        run: echo ${{secrets.DATABASE_URL}} > .env_docker

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{vars.DOCKERHUB_USERNAME}}/portfolio-server:latest

  Deploy:
    name: Run the docker image on host machine
    runs-on: ubuntu-latest
    needs: Containerize
    environment: "AWS Deployment"
    steps:
      - name: Start the deployment process
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.AWS_SSH_IP}}
          username: ${{secrets.AWS_SSH_USERNAME}}
          key: ${{secrets.AWS_SSH_KEY}}
          script: |
            docker pull ${{secrets.CONTAINER_NAME}}
            docker stop main-server
            docker rm main-server
            docker run -d -p 80:1323 --add-host host.docker.internal:host-gateway --name main-server kartorias1/portfolio-server:latest

